### PR TITLE
Network Rebuild Prototype

### PR DESCRIPTION
**Pull request by DavidOry**

### CODE REVIEW

**Comment by DavidOry** [comment]
@lmz 

Here are the SF Prototype Network Rebuild files. The PR contains a stray CreateFiveHighwayNetworks file that was created a long time ago, so probably not relevant, but it was sitting in our repo, so wanted to include it. 

The files we changed are in the `network-rebuild` dir.

**Comment by DavidOry** [comment]
Ah. Looks like `CreateFive...` change is in #21.

**Comment by lmz** [comment]
Is this pull request still legit?  Many of these files are data files which live on Box instead.  I thought network building scripts live in other repos (e.g. mainly https://github.com/BayAreaMetro/travel-model-two-networks/tree/develop, plus network_wrangler & lasso)

**Comment by DavidOry** [comment]
@i-am-sijia 
Can we close and discard this one given that `travel-model-two-networks` was created subsequent to this?

**Pull request closed without merging**
